### ISSUE TITLE
Add DigiByte Domains to See DigiAssets in action.

### ISSUE THREAD

**Issue by DGBNOOB** [DigiByte-Core/DigiByte.org#105]
DigiByte Domains is a service which utilizes the v3 DigiAsset protocol and issued domain names are digiassets. I recommend adding DigiByte Domains to "See DigiAssets in action" section.

Description of service:
A DigiByte domain is a name that references a public address. It's powered by DigiAssets and the domain is the asset.

PNG Icon:
https://digibytedomains.com/img/digibyte-domain-system.png

DigiByte Domains url:
https://digibytedomains.com/

![see digiassets in action](https://github.com/DigiByte-Core/DigiByte.org/assets/136190014/a0d745a0-6b76-4bef-b7bd-80f43ef9c32c)

**Comment by ycagel** [comment]
This has been resolved through PR https://github.com/DigiByte-Core/DigiByte.org/pull/106.
