### ISSUE TITLE
Remove donation links

### ISSUE THREAD

**Issue by DGBNOOB** [DigiByte-Core/DigiByte.org#107]
A few months back there was a dispute about book keeping issues on a supporting entity website. After a discussion about donation links on this website, it was decided to remove Donate button. The DigiByte.org website is for sharing general information about the blockchain and protocols to help spread awareness. The website is updated and maintained by volunteers and they are not responsible for supporting entity donations or book keeping. The donate to DigiByte organizations link directs the viewer to the dgbwiki, which is outdated and depreciated. That specific page is admin only, cannot be updated due to the unavailability of the admins or admins no longer in the community. 

The second link is to the DGBAT donation address, for anyone wanting to donate to the DigiByte Awareness Team, they can visit dgbat.org. 
 
Recommend removing the whole sentence, "Donate to digibyte organizations or use services below to support us"
![Contribute to the DigiByte community](https://github.com/DigiByte-Core/DigiByte.org/assets/136190014/e290b7da-dc12-4192-ac10-4a9360f9614b)

Recommend removing donate in the DigiByte Awareness Team description.
![Donate ](https://github.com/DigiByte-Core/DigiByte.org/assets/136190014/65b4203d-21cc-4121-af1d-57125b2ca2b6)

**Comment by ycagel** [comment]
This has been resolved through PR https://github.com/DigiByte-Core/DigiByte.org/pull/110.
