### ISSUE TITLE
ProDoge

### ISSUE THREAD

**Issue by DGBNOOB** [DigiByte-Core/DigiByte.org#109]
Prodoge recently rebranded to AXL wallet. The apps are no longer in the app store.
 
Recommend removing Prodoge from Point of sale apps

![Prodoge](https://github.com/DigiByte-Core/DigiByte.org/assets/136190014/f480fee8-02dc-46b8-9b33-fa493d6bf5a4)

![prodoge](https://github.com/DigiByte-Core/DigiByte.org/assets/136190014/e9ee621d-6442-4cd4-9840-db2075b3eebb)

**Comment by ycagel** [comment]
This has been resolved through PR https://github.com/DigiByte-Core/DigiByte.org/pull/110.
