### ISSUE TITLE
YouTube links

### ISSUE THREAD

**Issue by DGBNOOB** [DigiByte-Core/DigiByte.org#115]
The YouTube link at the top of the website and in the social media section need to be updated. The current YouTube link goes to the Josiah Spackman - DigiByte channel, the last video was from March 2022 titled "a lie a minute". 

I recommend changing the link from Josiah Spackman - DigiByte to the DigiByte Global Community YT channel. This channel has the latest videos starting December 2022 through March 2024.

Link: https://www.youtube.com/@DigiByteGlobalCommunity

![links at the top youtube](https://github.com/DigiByte-Core/DigiByte.org/assets/136190014/246fc633-265b-4b11-bc47-0e63fc5a240b)

![social media links youtube](https://github.com/DigiByte-Core/DigiByte.org/assets/136190014/f256b8e3-0e77-4df1-8b6e-f3a34f49bc33)

**Comment by ycagel** [comment]
This definitely needs to be changed.
