### ISSUE TITLE
DigiStats on DigiByte .org

### ISSUE THREAD

**Issue by DGBNOOB** [DigiByte-Core/DigiByte.org#122]
This issue is to add DigiStats to DigiByte .org. 
In my opinion there are two locations where Digistats would go well, the first location is at the top where the DigiByte monthly updates use to be. Instead of the wireless icon, change it to plain text to read “DigiStats”.

The second location is at the bottom of the page, a non-working and older version of DigiStats is located under DigiByte Links. 

First location
![DigiStats here](https://github.com/DigiByte-Core/DigiByte.org/assets/136190014/645e7b05-7ab0-48df-bad2-d30d1e4c6bf2)
Second location
![and here](https://github.com/DigiByte-Core/DigiByte.org/assets/136190014/d7b5febb-febf-4e63-97b2-4c2f26d74751)

**Comment by ycagel** [comment]
Someone would need to create this PR for it get reviewed.

**Comment by DennisPitallano** [comment]
updated the DigiStats link

![image](https://github.com/DigiByte-Core/DigiByte.org/assets/3394208/2cf0fd57-dc56-4c95-92b0-e85468303b16)

![image](https://github.com/DigiByte-Core/DigiByte.org/assets/3394208/4da5cb2e-fa50-4d92-9b9f-5b41c35cf4f1)

**Comment by DGBNOOB** [comment]
Dennis,
I personally like the icon and DigiStats together at the top. If no one has any objections or different recommendation then I’d like to see these changes added to PR #126.

**Comment by ycagel** [comment]
This was resolved through PR https://github.com/DigiByte-Core/DigiByte.org/pull/126

**Comment by ycagel** [comment]
This was resolved through PR https://github.com/DigiByte-Core/DigiByte.org/pull/126
