### ISSUE TITLE
Remove Trezor from Hard Wallet

### ISSUE THREAD

**Issue by DGBNOOB** [DigiByte-Core/DigiByte.org#129]
Trezor will discontinue support for DGB on their hardware wallet and the hardware wallet section needs to be updated. Recommendation is to remove Trezor from hardware wallet section.
![IMG_4830](https://github.com/user-attachments/assets/49e3e659-0d21-49cc-94e9-de46e4076293)

**Comment by ycagel** [comment]
https://github.com/DigiByte-Core/DigiByte.org/pull/130 has resolved this.
