### ISSUE TITLE
Update X thumbnail in Social Media

### ISSUE THREAD

**Issue by DGBNOOB** [DigiByte-Core/DigiByte.org#131]
It was recently brought up that the Twitter logo in the Community Social Media Section should be updated to reflect the new X logo. Recommendation: find or create an X logo using the color blue #1DA1F2 before continuing and creating a pull request to update the X logo.
![IMG_6293](https://github.com/user-attachments/assets/185e0d3b-65ce-4ead-a477-f0c35ae82943)

**Comment by ycagel** [comment]
Issue resolved with PR https://github.com/DigiByte-Core/DigiByte.org/pull/132
