### ISSUE TITLE
DigiAssets Learn the protocol.

### ISSUE THREAD

**Issue by DGBNOOB** [DigiByte-Core/DigiByte.org#57]
DigiAssets section

![Screenshot 2023-07-01 114749](https://github.com/DigiByte-Core/DGBio/assets/136190014/951bc9e4-a404-4e1f-afa3-89819e739633)

1. Learn the protocol
The current embedded link goes to an older version of the DigiAssets Specifications dated 2019: 

https://github.com/DigiByte-Core/DigiAssets-Protocol-Specifications/wiki/DigiAsset%20Scheme 

v3 DigiAssets-Protocol-Specifications is dated 2021. No Translation needed-recommend updating the link to: 

https://github.com/digiassetX/DigiAssets-Protocol-Specifications/blob/master/DigiAsset-Scheme.md

If you follow the link to DigiAssets Protocol Specifications from 2019 there was an issue opened titled Obsolete dated July 28, 2021. I see this as a needed update for anyone who is interested in working with v3 DigiAssets. 

These are some of the differences that stand out.
![Screenshot 2023-07-01 113244](https://github.com/DigiByte-Core/DGBio/assets/136190014/6a324685-7d5c-40ba-9b9a-b3e7cacd9c22)
![Screenshot 2023-07-01 113543](https://github.com/DigiByte-Core/DGBio/assets/136190014/0f535560-8bce-4eff-963d-279982d8c67d)

**Comment by Sbosvk** [comment]
We need to confirm with @digiAssetX whether this documentation is up-to-date, and then we can issue a pull request to have the repo under DigiByte Core org updated.

**Comment by DGBNOOB** [comment]
Just received a message from DigiAssetX and the documentation is not complete.  I'm not sure if this includes DigiAsset Core development but this issue should be put at the back of the line until the documentation is updated and complete.

**Comment by DGBNOOB** [comment]
Update on previous message DigiAsset Core documentation can be found at https://github.com/DigiAsset-Core.

**Comment by DennisPitallano** [comment]
Hi @DGBNOOB 
![image](https://github.com/DigiByte-Core/DGBio/assets/3394208/ed4c63b6-4948-44c6-8c6d-2377892882bc)

Just to confirm, we only need to update the link for "DigiAssets Protocol on GitHub" from https://github.com/digiassetX/DigiAssets-Protocol-Specifications/blob/master/DigiAsset-Scheme.md to https://github.com/DigiAsset-Core, correct?

**Comment by DGBNOOB** [comment]
Yes, that would be the only change. 

I want to add a little context for other reading, currently the digiasset protocol link directs you to the v1-v2 digiasset repository. v3 is the latest version with digiasset-core in alpha testing. @Sbosvk raised an issue to have the protocol update on the DigiAsset-Protocol-Specification repo on July 5, 2023. I think this should be updated because it opens the door for more developers to implement DigiAsset-Core and possibly make contributions to it and making the DigiByte ecosystem more robust. Again this is the only change link from from v1-v2 specifications to digiasset-core.
 
![Screenshot 2024-03-19 105059](https://github.com/DigiByte-Core/DGBio/assets/136190014/1d67c0fa-2f14-4c26-a248-300c5b09dbf5)

![Screenshot 2024-03-19 105322](https://github.com/DigiByte-Core/DGBio/assets/136190014/44443c51-f5a3-41fd-b4c7-e572c510bdc8)

**Comment by mctrivia** [comment]
I really need to finish the update.  It didn't play nice with my ide so was a bit of a pain to change.  I did document the protocol in great detail 

Here https://github.com/DigiAsset-Core/DigiAsset_Core/blob/master/src/DigiAsset.cpp#L406 and here https://github.com/DigiAsset-Core/DigiAsset_Core/blob/master/src/DigiAssetRules.cpp#L16

**Comment by DGBNOOB** [comment]
@DennisPitallano then the change would now be to add link to DigiAsset.cpp and a link to DigiAssetRules.ccp in place of link to DigiAsset Protocol on Github. It would then read **DigiAsset.cpp** with link to repo **and** **DigiAssetRules.ccp** with link to repo in @mctrivia comment above instead of DigiAsset Protocol on Github

**Comment by DennisPitallano** [comment]
@DGBNOOB 
like this?
![image](https://github.com/DigiByte-Core/DGBio/assets/3394208/42499ee7-bff0-43e0-a18f-dee4244f1327)

**Comment by DGBNOOB** [comment]
I think that should work, but obviously needs to get reviewed and then we can go from there.

**Comment by Sbosvk** [comment]
If we can just hold our horses for just a little bit on this there will hopefully be documentation ready by sometime next week, I am currently assisting Matthew in making it. I have a lot going on right now, I don't want to go into it here but @DGBNOOB is aware, so I don't know how much time I can put into it, but again, we will **try** to have something ready by sometime next week at the latest.

**Comment by DGBNOOB** [comment]
Sounds good @Sbosvk, 

@DennisPitallano we can hold here on this issue until the documentation is ready.

**Comment by DennisPitallano** [comment]
Sure, my PR is in draft, I'll make it ready once the documentations are available.

**Comment by DGBNOOB** [comment]
Sounds excellent,
Thank you to everyone in this conversation. I appreciate Matthew for sharing pertinent info on DigiAsset Core, I 100% value Sbosvk feedback and effort on this issue. Thank you Dennis for being patient and flexible through this process.

**Comment by ycagel** [comment]
Has the documentation been finished @Sbosvk? Thanks for all you are doing.

**Comment by mctrivia** [comment]
Yes there is a web server and docs here:

https://github.com/DigiAsset-Core/DigiAsset_Core/tree/master/web

DigiByte Core related docs:
https://github.com/DigiAsset-Core/DigiAsset_Core/tree/master/web/rpc

DigiAsset Core overrides and expansion:
https://github.com/DigiAsset-Core/DigiAsset_Core/tree/master/src/RPC/Methods

**Comment by ycagel** [comment]
> Yes there is a web server and docs here:
> 
> https://github.com/DigiAsset-Core/DigiAsset_Core/tree/master/web
> 
> DigiByte Core related docs: https://github.com/DigiAsset-Core/DigiAsset_Core/tree/master/web/rpc
> 
> DigiAsset Core overrides and expansion: https://github.com/DigiAsset-Core/DigiAsset_Core/tree/master/src/RPC/Methods

We just need a PR for this to get it reviewed.

**Comment by DGBNOOB** [comment]
> > Yes there is a web server and docs here:
> > https://github.com/DigiAsset-Core/DigiAsset_Core/tree/master/web
> > DigiByte Core related docs: https://github.com/DigiAsset-Core/DigiAsset_Core/tree/master/web/rpc
> > DigiAsset Core overrides and expansion: https://github.com/DigiAsset-Core/DigiAsset_Core/tree/master/src/RPC/Methods
> 
> We just need a PR for this to get it reviewed.

@ycagel this issue is to have the URL link updated from the DigiAssets v1-v2 specification on GitHub which are outdated, to DigiAsset Core with the current version and developments to the protocol. I'm curious to why a PR is needed. The v1-v2 DigiAsset specification and repository are obsolete and that is where the website will direct anyone clicking the link on DigiByte .org. I think this is a setback for getting more developers working with v3 DigiAssets. This change is not to add DigiAsset-Core to the DigiByte-Core organization.

@DennisPitallano In my opinion the link should be labeled DigiAsset-Core with (1) link [DigiAsset-Core](https://github.com/DigiAsset-Core/DigiAsset_Core). https://github.com/DigiAsset-Core/DigiAsset_Core

@mctrivia please add your input on what the link should be labeled and if it goes to any specific file or folder.

Thank you all, lets move this forward.

**Comment by DGBNOOB** [comment]
@ycagel I think i might have read your last reply wrong, if your saying submit a PR to have this change made then disregard my comment. I did make a recommendation and we should wait for input before creating PR.

**Comment by DennisPitallano** [comment]
> > > Yes there is a web server and docs here:
> > > https://github.com/DigiAsset-Core/DigiAsset_Core/tree/master/web
> > > DigiByte Core related docs: https://github.com/DigiAsset-Core/DigiAsset_Core/tree/master/web/rpc
> > > DigiAsset Core overrides and expansion: https://github.com/DigiAsset-Core/DigiAsset_Core/tree/master/src/RPC/Methods
> > 
> > 
> > We just need a PR for this to get it reviewed.
> 
> @ycagel this issue is to have the URL link updated from the DigiAssets v1-v2 specification on GitHub which are outdated, to DigiAsset Core with the current version and developments to the protocol. I'm curious to why a PR is needed. The v1-v2 DigiAsset specification and repository are obsolete and that is where the website will direct anyone clicking the link on DigiByte .org. I think this is a setback for getting more developers working with v3 DigiAssets. This change is not to add DigiAsset-Core to the DigiByte-Core organization.
> 
> @DennisPitallano In my opinion the link should be labeled [DigiAsset-Core](https://github.com/DigiAsset-Core/DigiAsset_Core) and only (1) link https://github.com/DigiAsset-Core/DigiAsset_Core
> 
> @mctrivia please add your input on what the link should be labeled and if it goes to any specific file or folder.
> 
> Thank you all, lets move this forward.

That makes sense @DGBNOOB .
I've deployed the web documentation from my fork (https://github.com/DennisPitallano/DigiAsset_Core) to make it accessible directly on the web. You can view it here: https://digi-asset-core.vercel.app/.

I'll remove the related commit from my PR so we can address issue #121 on the main repository (https://github.com/DigiByte-Core/DigiByte.org/issues/121). We can create a new PR once this is resolved.

**Comment by DGBNOOB** [comment]
@mctrivia will need to take a look, this is a little more technical than I can understand. It looks like a developer who understands the RPC calls will know how to implement the protocol. I just have one question, will any changes @mctrivia makes to DigiAsset-Core automate onto this app?  
Great job Dennis.

**Comment by mctrivia** [comment]
@DGBNOOB I am not sure what you mean by "changes automated on to this app"

**Comment by DGBNOOB** [comment]
@mctrivia thank you for the quick response. Like I said this is a little more technical than I understand. [6c1256a ](https://github.com/DigiByte-Core/DigiByte.org/commit/6c1256aafb27675ff3cf4958b5028cdbb82d43dc) Looks like it adds a link to DigiAsset-Core repository and a link to all the RPC calls. If this looks good to you then we can recommend to have it approved so that it can be added to DigiByte .org.

**Comment by ycagel** [comment]
Resolved through PR https://github.com/DigiByte-Core/DigiByte.org/pull/125
