### ISSUE TITLE
DigiByte Mobile app image

### ISSUE THREAD

**Issue by DGBNOOB** [DigiByte-Core/DigiByte.org#59]
Recommend replacing the DigiByte Mobile Image with DigiByte logo. No translation required

For anyone visiting the website, the first thing that you see is an image of the DigiByte Mobile application. The application had great features, however, since I’ve been in the community it’s been more of a detractor due to failing to sync and new versions of android no longer support the app. Recommend replacing the mobiles image with a DigiByte logo as a place holder until a newer image can replace the logo. If users choose to down load and use the iOS/Android wallet app, that's at their own risk. This isn't a recommendation to sunset the app, it's a recommendation to change the website image. 

Alternative solutions and recommendations welcomed.

![Screenshot 2023-07-01 125456](https://github.com/DigiByte-Core/DGBio/assets/136190014/6fb692a1-ba24-4f85-b3bc-93da4ee631fe)
![512x512](https://github.com/DigiByte-Core/DGBio/assets/136190014/12696731-c32d-49ca-933e-80aefa63b4b1)

**Comment by Sbosvk** [comment]
I agree, must be removed. Negative impact outweighs positive.

**Comment by Sbosvk** [comment]
Would be great if we could get some user submissions of replacement graphic for this.

**Comment by DGBNOOB** [comment]
I just shared a tweet for more recommendations on a replacement image, I’ll see if the community can come up with different image.

**Comment by Sbosvk** [comment]
Thank you @DGBNOOB. Please ask them to submit their proposal graphics to this issue thread.

**Comment by DGBNOOB** [comment]
One week ago today I started a Twitter poll to get feed back on graphic proposal to replace the DigiByte mobile wallet image. The poll included (3) options, 1. was the DigiByte blockchain logo, 2. was the D DigiByte logo and 3. was other. 107 votes, 75% voted for option 1, 17% voted for option 2 and 8% voted other. There was one comment to leave the current image. I'll attach a screenshot of the twitter thread. No one submitted a proposal graphic.    

![1](https://github.com/DigiByte-Core/DGBio/assets/136190014/3da7b4b4-3f29-494a-a9fc-fae1bd2f5119)
![2](https://github.com/DigiByte-Core/DGBio/assets/136190014/2d17ec8c-6f8b-4eb6-8ef5-48f60c12ed7d)
![3](https://github.com/DigiByte-Core/DGBio/assets/136190014/18964b3d-1328-4b17-8f62-8419c76847d8)

**Comment by DGBNOOB** [comment]
Thank you for removing the mobile wallet image, I can barely remember it being there. I'll leave this issue open for now and can close it if there are plans in place for a replacement image.

**Comment by Sbosvk** [comment]
I think we probably do want some sort of replacement. On small screen devices the page looks just fine, but looks a bit empty on bigger screens. So yes, let's leave the issue open for now.

**Comment by ycagel** [comment]
Can this issue be closed now?

**Comment by Sbosvk** [comment]
I am working on an image that we can hopefully agree on as a replacement. No ETA, but I am about 70% done.
It's a vector graphic with ~100 paths, and I plan on making it into an animation. (which reminds me we need to add function to remove animations completely for people with conditions such as epilepsy. I will create an issue for this with more details soon)

**Comment by ycagel** [comment]
How are we looking on this @Sbosvk? Thanks for all your hard work.

**Comment by DGBNOOB** [comment]
Closing this issue, there is an alternative solution being worked on by @Sbosvk.
