### ISSUE TITLE
What is Digi-ID video

### ISSUE THREAD

**Issue by DGBNOOB** [DigiByte-Core/DigiByte.org#68]
Authentication at its best Digi-ID section

No translation required.
Recommend removing the What is Digi-ID video. Same as issue #67 and issue #59, at the end of the video it says "download the DigiByte wallet today and get started using Digi-ID" (1:36) on the time. Replace with temporary image until a different video is created.

![Screenshot 2023-07-01 175756](https://github.com/DigiByte-Core/DGBio/assets/136190014/1047d5f4-f718-4ea4-981a-574a628faed8)

**Comment by Sbosvk** [comment]
This video does not actually ever refer to the DigiByte Mobile wallet in a way that I feel is prominent enough to trigger a removal of the video.

**Comment by DGBNOOB** [comment]
Thank you for your input, I will close the issues pertaining to the videos. Maybe in the future, if we can get updated videos then we can revisit and reconsider replacing the current videos on the website.
