### ISSUE TITLE
Web page broken please fix it 

### ISSUE THREAD

**Issue by Decentralised123** [DigiByte-Core/DigiByte.org#75]
From past month
![Screenshot_20231118-223244](https://github.com/DigiByte-Core/DGBio/assets/151392416/c77ebf2b-e2c3-49cd-9d1f-a8454906ff79)
 I'm seeing this broken webpage , desktop view is fine the issue is only for mobile version

**Comment by Sbosvk** [comment]
This issue is the result of too great of resolution on mobile devices. However, this is not the correct repository under which to open this issue. Please open it under DigiByte-Core/DGBio

**Comment by DennisPitallano** [comment]
Hi @Decentralised123 @Sbosvk 
I believe this matter has already been resolved.

https://github.com/DigiByte-Core/DGBio/assets/3394208/5bb5e2af-39dc-4392-baad-419858898871

we can proceed with closing this issue.

**Comment by Decentralised123** [comment]
Thank you 😊 website is working perfect now shows both slides and stats

**Comment by Sbosvk** [comment]
@DennisPitallano  don't see how it could have been fixed. Reporters have said the issues seem intermittent so I wouldn't be so sure we have gotten rid of this. I will do some testing to try and verify.

**Comment by Sbosvk** [comment]
### Tests

| Device | Resolution | Result |
|--:--|--:--|
| iPhone 12 Pro | 390x844 | ✅ |
| iPad | 768x1024 | ✅ |
| MacBook Pro | 1440x900 | ✅ |
| Surface Pro 7 | 912x1368 | ✅ |
| Nexus 10 | 800x1280 | ✅ |
| Nest Hub Max | 1280x800 | ✅ |
| Realme 5 | 720x1600 | ✅ |


All tests pass. Will close this issue.
