### ISSUE TITLE
Community Section-DigiByte Alliance only appears in English version of the website

### ISSUE THREAD

**Issue by DGBNOOB** [DigiByte-Core/DigiByte.org#86]
In the community section, the DigiByte Alliance is only on the English version of the website. The top screenshot example is of the English version, which includes DigiByte Foundation, Alliance, DGBAT, and Developers not captured in this screenshot right below. The second screenshot is of the Spanish version, which only has the Foundation, DGBAT and Developers. Recommend adding DigiByte Alliance to the other language versions of the website. 

![Community DigiByte Alliance English](https://github.com/DigiByte-Core/DGBio/assets/136190014/703db43e-ff92-4017-9846-193590cde432)
![Community no DigiByte Alliance](https://github.com/DigiByte-Core/DGBio/assets/136190014/5240e8e9-33ec-45f8-9e4d-bc0c884819a1)

**Comment by DGBNOOB** [comment]
We should also add DigiByte Alliance in the links at the bottom of the page with DGB Awareness Team.
![DigiByte Alliance](https://github.com/DigiByte-Core/DGBio/assets/136190014/1c7ab306-3e26-400f-8f9c-cf809cd37d81)

**Comment by ycagel** [comment]
Are we able to include this in the next PR?

**Comment by DennisPitallano** [comment]
Should we go ahead with the requested change?
Other languages are also affected, and I've included translations below. Just need a quick proofread of the translations.

1. **Spanish (Spain)**:
   La Alianza DigiByte es una fundación pública sin fines de lucro bajo la sección 501(c)(3) con estatus de caridad pública en los EE. UU. Su objetivo es solidificar a DigiByte como una red blockchain confiable y descentralizada para proteger, asegurar, expresar, crear y transferir valor de manera confiable y eficiente.
   Para obtener más información, contacta.

2. **French (France)**:
   L'Alliance DigiByte est une fondation publique à but non lucratif sous la section 501(c)(3) avec le statut de charité publique aux États-Unis. Leur objectif est de solidifier DigiByte en tant que réseau blockchain fiable et décentralisé pour protéger, sécuriser, exprimer, créer et transférer de la valeur de manière fiable et efficace.
   Pour en savoir plus - Contactez.

3. **German (Germany)**:
   Die DigiByte Alliance ist eine öffentliche gemeinnützige Stiftung gemäß Abschnitt 501(c)(3) mit öffentlichem Wohltätigkeitsstatus in den USA. Sie zielt darauf ab, DigiByte als vertrauenswürdiges und dezentrales Blockchain-Netzwerk zu festigen, um Wert zuverlässig und effizient zu schützen, zu sichern, auszudrücken, zu erstellen und zu übertragen.
   Erfahren Sie mehr - Kontaktieren Sie uns.

4. **Portuguese (Brazil)**:
   A Aliança DigiByte é uma fundação pública sem fins lucrativos sob a seção 501(c)(3) com status de caridade pública nos EUA. Eles têm como objetivo solidificar o DigiByte como uma rede blockchain confiável e descentralizada para proteger, segurar, expressar, criar e transferir valor de forma confiável e eficiente.
   Saiba mais - Contato.

5. **Chinese (Mandarin)**:
   DigiByte联盟是在美国公共慈善法501(c)(3)部门下具有公益慈善资格的公共非营利基金会。他们的目标是将DigiByte确立为可靠且去中心化的区块链网络，可可靠且高效地保护、安全、表达、创建和传输价值。
   了解更多信息 - 联系我们。

6. **Russian (Russia)**:
   Альянс DigiByte - это общественный некоммерческий фонд по разделу 501(c)(3) с общественным благотворительным статусом в США. Они стремятся укрепить DigiByte как доверенную и децентрализованную блокчейн-сеть для надежной и эффективной защиты, обеспечения, выражения, создания и передачи ценности.
   Узнать больше - Связаться.

7. **Arabic (Modern Standard Arabic)**:
   تعد تحالف DigiByte مؤسسة عامة غير ربحية بموجب القسم 501(c)(3) بصفة مؤسسة خيرية عامة في الولايات المتحدة. يهدفون إلى ترسيخ DigiByte كشبكة بلوكشين موثوقة ولامركزية لحماية وتأمين والتعبير وإنشاء ونقل القيمة بشكل موثوق وفعال.
   لمعرفة المزيد - اتصل بنا.

8. **Japanese**:
   DigiByteアライアンスは、米国の501(c)(3)節に基づく公共慈善団体としての公共非営利財団です。彼らの目標は、信頼性の高い分散型ブロックチェーンネットワークであるDigiByteを確立し、価値を信頼性高く効率的に保護、保護、表現、作成、転送することです。
   詳細については、お問い合わせください。

9. **Hindi (India)**:
   DigiByte संघ एक सार्वजनिक गैर-लाभकारी संस्था है जिसके पास सेक्शन 501(c)(3) के तहत अमेरिका में सार्वजनिक चैरिटी स्थिति है। उनका उद्देश्य DigiByte को एक विश्वसनीय और डीसेंट्रलाइज्ड ब्लॉकचेन नेटवर्क के रूप में मजबूत करना है ताकि मूल्य को विश्वसनीयता और कुशलता से सुरक्षित, सुरक्षित, व्यक्त किया जा सके और मान्यता दी जा सके।
   अधिक जानें - संपर्क करें।

**Comment by DGBNOOB** [comment]
My recommendation is the same as on issue #92 for the translation and proofreading part.

**Comment by DennisPitallano** [comment]
Translations have been implemented.

1. Arabic (Modern Standard Arabic):
تعد تحالف DigiByte مؤسسة عامة غير ربحية بموجب القسم 501(c)(3) بصفة مؤسسة خيرية عامة في الولايات المتحدة. يهدفون إلى ترسيخ DigiByte كشبكة بلوكشين موثوقة ولامركزية لحماية وتأمين والتعبير وإنشاء ونقل القيمة بشكل موثوق وفعال.
لمعرفة المزيد - اتصل بنا.
2. Afrikaans:
Die DigiByte Alliansie is 'n openbare nie-winsgewende stigting onder afdeling 501(c)(3) met openbare liefdadigheidstatus in die VSA. Hulle mik daarop om DigiByte te versterk as 'n betroubare en gedesentraliseerde blokkettingnetwerk om waarde betroubaar en doeltreffend te beskerm, beveilig, uit te druk, te skep en oor te dra.
Leer meer - Kontak.
3. Czech:
DigiByte Alliance je veřejná nezisková nadace pod oddílem 501(c)(3) se statutem veřejné dobročinnosti ve Spojených státech. Jejich cílem je upevnit DigiByte jako důvěryhodnou a decentralizovanou blockchainovou síť pro spolehlivou a efektivní ochranu, zajištění, vyjádření, vytváření a přenos hodnot.
Více informací - Kontakt.
4.  Danish:
DigiByte Alliance er en offentlig non-profit fond under afsnit 501(c)(3) med offentlig velgørenhedsstatus i USA. Deres mål er at solidificere DigiByte som et betroet og decentraliseret blockchain-netværk til pålideligt og effektivt at beskytte, sikre, udtrykke, skabe og overføre værdi.
Læs mere - Kontakt.
5. German (Germany):
Die DigiByte Alliance ist eine öffentliche gemeinnützige Stiftung gemäß Abschnitt 501(c)(3) mit öffentlichem Wohltätigkeitsstatus in den USA. Sie zielt darauf ab, DigiByte als vertrauenswürdiges und dezentrales Blockchain-Netzwerk zu festigen, um Wert zuverlässig und effizient zu schützen, zu sichern, auszudrücken, zu erstellen und zu übertragen.
Erfahren Sie mehr - Kontaktieren Sie uns.
6. Spanish (Spain):
La Alianza DigiByte es una fundación pública sin fines de lucro bajo la sección 501(c)(3) con estatus de caridad pública en los EE. UU. Su objetivo es solidificar a DigiByte como una red blockchain confiable y descentralizada para proteger, asegurar, expresar, crear y transferir valor de manera confiable y eficiente.
Para obtener más información, contacta.
7. French (France):
L'Alliance DigiByte est une fondation publique à but non lucratif sous la section 501(c)(3) avec le statut de charité publique aux États-Unis. Leur objectif est de solidifier DigiByte en tant que réseau blockchain fiable et décentralisé pour protéger, sécuriser, exprimer, créer et transférer de la valeur de manière fiable et efficace.
Pour en savoir plus - Contactez.
8. Croatian:
DigiByte Savez je javna neprofitna fondacija pod odjeljkom 501(c)(3) sa statusom javne dobrotvornosti u SAD-u. Cilj im je učvrstiti DigiByte kao pouzdanu i decentraliziranu blockchain mrežu kako bi pouzdano i efikasno zaštitili, osigurali, izrazili, stvorili i prenijeli vrijednost.
Saznajte više - Kontakt.
9. Indonesian:
Aliansi DigiByte adalah yayasan nirlaba publik di bawah bagian 501(c)(3) dengan status amal publik di Amerika Serikat. Mereka bertujuan untuk memperkuat DigiByte sebagai jaringan blockchain yang terpercaya dan terdesentralisasi untuk melindungi, menjamin, mengungkapkan, menciptakan, dan mentransfer nilai dengan andal dan efisien.
Pelajari lebih lanjut - Hubungi.
10. Italian:
DigiByte Alliance è una fondazione pubblica non a scopo di lucro ai sensi della sezione 501(c)(3) con lo status di pubblica beneficenza negli Stati Uniti. Il loro obiettivo è consolidare DigiByte come una rete blockchain affidabile e decentralizzata per proteggere, garantire, esprimere, creare e trasferire valore in modo affidabile ed efficiente.
Per saperne di più - Contatto.
11. Swahili:
Umoja wa DigiByte ni shirika la hisani la umma katika sehemu ya 501(c)(3) na hadhi ya hisani ya umma nchini Marekani. lengo lao ni kusaidia DigiByte kama mtandao wa blockchain wa kuaminika na usiopangwa kuhakikisha, kuhakikisha, kueleza, kujenga na kusambaza thamani kwa njia ya kuaminika na yenye ufanisi.
Jifunze zaidi - Wasiliana.
12. Hungarian:
A DigiByte Alliance egy nyilvános nonprofit alapítvány az 501(c)(3) fejezet szerint, közhasznú jogállással az Egyesült Államokban. Céljuk a DigiByte megerősítése mint megbízható és decentralizált blockchain hálózat, hogy megbízhatóan és hatékonyan védjék, biztosítsák, kifejezzék, teremtsék és továbbítsák az értéket.
További információk - Kapcsolat.
13. Malay:
DigiByte Alliance adalah sebuah yayasan amal awam di bawah bahagian 501(c)(3) dengan status amal awam di Amerika Syarikat. Matlamat mereka adalah untuk mengukuhkan DigiByte sebagai rangkaian blockchain yang dipercayai dan terdesentralisasi untuk melindungi, menjamin, menyatakan, mencipta dan memindahkan nilai dengan boleh dipercayai dan efisien.
Ketahui lebih lanjut - Hubungi.
14. Dutch:
De DigiByte Alliance is een publieke non-profit stichting onder sectie 501(c)(3) met de status van publieke liefdadigheid in de VS. Ze streven ernaar om DigiByte te versterken als een vertrouwd en gedecentraliseerd blockchain-netwerk om waarde betrouwbaar en efficiënt te beschermen, beveiligen, uiten, creëren en over te dragen.
Leer meer - Neem contact op.
15. Norwegian:
DigiByte Alliance er en offentlig veldedighetsorganisasjon under seksjon 501(c)(3) med en offentlig veldedighetsstatus i USA. Målet deres er å styrke DigiByte som et pålitelig og desentralisert blockchain-nettverk for å beskytte, garantere, uttrykke, skape og overføre verdi på en pålitelig og effektiv måte.
Lær mer - Kontakt.
16. Tagalog:
Ang DigiByte Alliance ay isang pampublikong organisasyon ng kawanggawa sa seksyon 501(c)(3) na may pampublikong status ng kawanggawa sa Estados Unidos. Layunin nila na palakasin ang DigiByte bilang isang mapagkakatiwalaang at desentralisadong network ng blockchain upang protektahan, siguruhin, ipahayag, lumikha, at magpadala ng halaga sa isang mapagkakatiwalaan at epektibong paraan.
Alamin pa - Kontak
17. Polish:
DigiByte Alliance to publiczna organizacja charytatywna z sekcji 501(c)(3) o statusie charytatywnym w Stanach Zjednoczonych. Ich celem jest wzmocnienie DigiByte jako zaufanej i zdecentralizowanej sieci blockchain, aby wartość była bezpieczna i skutecznie chroniona, gwarantowana, wyrażana, tworzona i przekazywana.
Dowiedz się więcej - Kontakt.
18. Portuguese:
A Aliança DigiByte é uma organização beneficente pública na seção 501(c)(3) com status de caridade pública nos Estados Unidos. Seu objetivo é fortalecer o DigiByte como uma rede blockchain confiável e descentralizada para proteger, garantir, expressar, criar e transmitir valor de forma confiável e eficaz.
Saiba mais - Contato.
19. Romanian:
Alianța DigiByte este o organizație de caritate publică în secțiunea 501(c)(3) cu statut de caritate publică în Statele Unite. Scopul lor este de a întări DigiByte ca o rețea blockchain de încredere și descentralizată pentru a proteja, garanta, exprima, crea și transfera valoarea în moduri de încredere și eficiente.
Aflați mai multe - Contact.
20. Albanian:
Aleanca DigiByte është një themel organizatë publike pa fitim nën seksionin 501(c)(3) me statusin e bamirësisë publike në Shtetet e Bashkuara. Ata synojnë të solidifikojnë DigiByte si një rrjet bllokchain i besueshëm dhe i decentralizuar për të mbrojtur, siguruar, shprehur, krijuar dhe transferuar vlerë me besueshmëri dhe efikasitet.
Mësoni më shumë - Kontaktoni.
21. Slovenian:
DigiByte Alliance je javna dobrodelna organizacija v odseku 501(c)(3) z javnim statusom dobrodelnosti v Združenih državah. Njihov cilj je okrepiti DigiByte kot zanesljivo in decentralizirano omrežje veriženja blokov, da bi vrednost varno in učinkovito zaščitila, zagotovila, izražala, ustvarila in prenesla.
Izvedite več - Kontakt.
22. Finnish:
DigiByte Alliance on julkinen voittoa tavoittelematon säätiö osiossa 501(c)(3) ja julkisen hyväntekeväisyysaseman Yhdysvalloissa. Heidän tavoitteenaan on vahvistaa DigiBytea luotettavana ja hajautettuna lohkoketjuna suojaamaan, varmistamaan, ilmaisemaan, luomaan ja siirtämään arvoa luotettavasti ja tehokkaasti.
Lue lisää - Ota yhteyttä.
23. Swedish:
DigiByte Alliance är en offentlig välgörenhetsorganisation i avsnitt 501(c)(3) med status som offentlig välgörenhet i USA. Deras mål är att stärka DigiByte som en pålitlig och decentraliserad blockchain-nätverk för att skydda, garantera, uttrycka, skapa och överföra värde på ett pålitligt och effektivt sätt.
Lär dig mer - Kontakt.
24. Vietnamese:
Liên minh DigiByte là một tổ chức từ thiện công cộng trong phần 501(c)(3) với tư cách từ thiện công cộng tại Hoa Kỳ. Mục tiêu của họ là tăng cường DigiByte như một mạng lưới blockchain đáng tin cậy và phi tập trung để bảo vệ, đảm bảo, diễn đạt, tạo ra và chuyển giá trị một cách đáng tin cậy và hiệu quả.
Tìm hiểu thêm - Liên hệ.
25. Turkish:
DigiByte Alliance, Amerika Birleşik Devletleri'nde kamu hayır kurumları bölümü 501(c)(3) kategorisinde bir kamu hayır kurumu olarak hizmet verir. Amacı, DigiByte'ı güvenilir ve merkezi olmayan bir blockchain ağı olarak güçlendirmek ve değeri güvenilir ve etkili bir şekilde korumak, garanti etmek, ifade etmek, oluşturmak ve iletmektir.
Daha fazla bilgi edinin - İletişim.
26. Russian:
Альянс DigiByte - это общественная благотворительная организация в разделе 501(c)(3) с общественным статусом благотворительности в Соединенных Штатах. Их цель - укрепить DigiByte как надежную и децентрализованную сеть блокчейн для защиты, гарантирования, выражения, создания и передачи ценности надежным и эффективным способом.
Узнать больше - Контакт.
27. Bulgarian:
Сдружението DigiByte е обществена непечеливша организация по раздел 501(с)(3) с публичен благотворителен статут в САЩ. Те целят да утвърдят DigiByte като надеждна и децентрализирана блокчейн мрежа, за да защитават, осигуряват, изразяват, създават и пренасят стойност надеждно и ефективно.
Научете повече - Свържете се.
28. Greek:
Η Συμμαχία DigiByte είναι μια δημόσια μη κερδοσκοπική ιδρυματική ενότητα με διακριτικό 501(c)(3) με καθεστώς δημόσιας φιλανθρωπίας στις Ηνωμένες Πολιτείες. Στόχος τους είναι να στερεώσουν το DigiByte ως ένα αξιόπιστο και αποκεντρωμένο δίκτυο blockchain για να προστατεύει, να εξασφαλίζει, να εκφράζει, να δημιουργεί και να μεταφέρει αξία αξιόπιστα και αποτελεσματικά.
Μάθετε περισσότερα - Επικοινωνία.
29. Hindi:
DigiByte संघ एक सार्वजनिक गैर-लाभकारी संस्था है जिसके पास सेक्शन 501(c)(3) के तहत अमेरिका में सार्वजनिक चैरिटी स्थिति है। उनका उद्देश्य DigiByte को एक विश्वसनीय और डीसेंट्रलाइज्ड ब्लॉकचेन नेटवर्क के रूप में मजबूत करना है ताकि मूल्य को विश्वसनीयता और कुशलता से सुरक्षित, सुरक्षित, व्यक्त किया जा सके और मान्यता दी जा सके।
अधिक जानें - संपर्क करें।
30. Thai:
พันธมิตร DigiByte เป็นองค์กรกุศลสาธารณะในส่วน 501(c)(3) ด้วยสถานะการกุศลสาธารณะในสหรัฐอเมริกา จุดมุ่งหมายของพวกเขาคือการเสริมสร้าง DigiByte เป็นเครือข่ายบล็อกเชนที่น่าเชื่อถือและไม่มีการกำหนดเพื่อปกป้อง รับประกัน แสดง สร้าง และส่งมอบค่าในวิธีที่เชื่อถือได้อย่างมีประสิทธิภาพ
เรียนรู้เพิ่มเติม - ติดต่อ.
31. Japanese:
DigiByteアライアンスは、米国の501(c)(3)節に基づく公共慈善団体としての公共非営利財団です。彼らの目標は、信頼性の高い分散型ブロックチェーンネットワークであるDigiByteを確立し、価値を信頼性高く効率的に保護、保護、表現、作成、転送することです。
詳細については、お問い合わせください。
32. Korean:
DigiByte Alliance는 미국에서 공익단체인 501(c)(3) 항에 따라 공익단체로 승인된 공공 비영리 재단입니다. 그들의 목표는 신뢰할 수 있고 분산된 블록체인 네트워크로 DigiByte를 견고하게 만들어 가치를 신뢰할 수 있고 효과적으로 보호, 보장, 표현, 창조 및 전송하는 것입니다.
더 알아보기 - 연락처.
33. Chinese (Simplified):
 DigiByte联盟是在美国公共慈善法501(c)(3)部门下具有公益慈善资格的公共非营利基金会。他们的目标是将DigiByte确立为可靠且去中心化的区块链网络，可可靠且高效地保护、安全、表达、创建和传输价值。
 了解更多信息 - 联系我们
34. Persian:
اتحادیه دیجی‌بایت یک سازمان امورخیریه عمومی به موجب بخش 501(c)(3) با استاتوس امور خیریه عمومی در ایالات متحده آمریکا است. هدف آن‌ها تقویت دیجی‌بایت به عنوان یک شبکه بلاک‌چین قابل اعتماد و غیرمتمرکز است تا ارزش را به صورت قابل اعتماد و با کارایی محافظت، تضمین، بیان، ایجاد و انتقال دهد.
بیشتر بدانید - تماس.

**Comment by ycagel** [comment]
This has been resolved through PR https://github.com/DigiByte-Core/DigiByte.org/pull/104.
