### ISSUE TITLE
Apps developed by the community

### ISSUE THREAD

**Issue by DGBNOOB** [DigiByte-Core/DigiByte.org#93]
This issue is being opened to address issue #70 which was closed due to change in recommendations.

New recommendations:

1. Change header to read "DigiByte Core Client".
2. Remove all the text below about "DigiByte core, disc space and simplified software wallets" and leave it blank. 
4. Remove the DigiByte Mobile box and the links to iOS App Store, Google Play, Test flight, Android Beta and Support.
5. Add Recovery tool below Support and Run a full node in the DigiByte Core box.

In my opinion this meets the criteria for downloads since users can down load DigiByte Core for different operating systems. This change helps emphasize that DigiByte Core is the only official DigiByte wallet. If the user continues down on the website they will find third party soft and hardware wallets, and disclaimer. 

![downloads](https://github.com/DigiByte-Core/DGBio/assets/136190014/24465509-273e-4202-ae0f-d2d296cc7287)

**Comment by Sbosvk** [comment]
1. Why?
2. Not the worst idea. But I would still like some kind of disclaimer, but it could be moved to below the cards.
3. Absolutely, but this require some restructuring of the DigiByte Core card, as well as positioning, definitely possible but takes some tinkering.
4. Frankly I think this should be removed and possibly added elsewhere in the future.


Overall I think these are good thoughts.

**Comment by DGBNOOB** [comment]
> 1. Why?
> 2. Not the worst idea. But I would still like some kind of disclaimer, but it could be moved to below the cards and definitely re-worded.
> 3. Absolutely, but this require some restructuring of the DigiByte Core card, as well as positioning, definitely possible but takes some tinkering.
> 4. Frankly I think this should be removed and possibly added elsewhere in the future.
> 
> Overall I think these are good thoughts.

Recommendation 1. Change the sub header from “Apps developed by the DigiByte Community” to DigiByte-Core Client. In the top menu the “Downloads” option redirects you to this section with “Choose your app”. Seems a little redundant to state it again in “Apps developed by the DigiByte community”, especially if the DigiByte mobile card gets removed. If the viewer scrolls down a little further they will find different apps. In my opinion, the different OS versions of DigiByte-Core meet the criteria for “Downloads”. 

Recommendation 2. Removing text/ disclaimer. If the first recommendation is approved then I think it’s straight forward, DigiByte-Core Client and the different OS Download options are in the card. However, not against having a disclaimer- “DigiByte-Core is the official wallet of the DigiByte blockchain”, something along those lines to clarify between mobile apps/core wallet/official wallet-just a suggestion.

Recommendation 3. If the recovery tool is moved somewhere else then the DigiByte Core card doesn't have to change. 

Recommendation 4. The thought behind this change is to keep the “Recovery Tool” available and near “Support”, in the DigiByte Core card to help with troubleshooting if it’s a recovery issue. If it’s moved to another location that would work too, but I also think “support” and “recovery tool” should be collocated.

**Comment by Sbosvk** [comment]
1. Aha, I misunderstood. I thought you meant to change the header of the card from "DigiByte Core" to "DigiByte Core Client".

2. I think it makes sense to have a disclaimer that states DigiByte Core wallet should be used by advanced users. I also think the current description under the header should read something of the likes of DigiByte Core being the core protocol and can be ran to contribute to the network.

4. The troubleshooting tool will link to the recovery tool. I don't think we should immediately link to a tool that has a fee, especially not without disclaimers of sharing private keys or mnemonic seeds, and disclaimer about the fee, regardless how helpful it is. It makes more sense to have users go through troubleshooting guide to get there as this is hosted on digiassetX platform.

**Comment by DGBNOOB** [comment]
I think your recommendations make a lot of sense. After looking at the changes, the only change that needs to happen is removing the DigiByte mobile card. Rewording the sub header really isn’t necessary, however, if there is a change made my recommendation is “DigiByte-Core Client”. I agree with having the disclaimer, and the current text meets the criteria about being the backbone of the network and if you’re not an experienced user try using a software wallet. I think the current disclaimer is fine unless you want to reword it. 
I clicked on the support icon which takes you through troubleshooting and the (12-24 word) recovery tool is an option, plus it also prompts you to seek further assistance in the telegram support channel. Adding the recovery tool to the core wallet card is not necessary, however, I agree with one of your previous recommendations about finding a different place for it, since the recovery tool “DigiSweep” is a service that helps recover DGB and DigiAssets-then I think it’s appropriate to add it to the DigiAsset supported services section, which can be a different issue. 

My recommendation now is to only remove the DigiByte mobile card and information in it, but if you have recommendations on rewording the sub header or the disclaimer, maybe share them in the next response so that this issue can be resolved. 
Lastly, I appreciate and value your feedback, it helps me look at the issue from different points of view.

**Comment by Sbosvk** [comment]
Working on this.

**Comment by Sbosvk** [comment]
![Screenshot from 2024-04-10 20-12-02](https://github.com/DigiByte-Core/DigiByte.org/assets/43497491/af5ee758-f49d-4b38-a570-3a38937a9e39)

@DGBNOOB Please share your opinion on this

**Comment by ycagel** [comment]
I would change to All in One

**Comment by Sbosvk** [comment]
@ycagel  Hahaha, that is just typical. I was so close to DMing you on Telegram to ask you whether you thought "all-in-one" or "all in one" but then I didn't. Absolutely, can change it.

**Comment by DGBNOOB** [comment]
This looks great, I think better than i had pictured it. I like the header,  description didn't have to change, I like the DigiByte logo, and the disclaimer makes a lot sense.  Great job @Sbosvk

**Comment by ycagel** [comment]
This has been resolved through PR https://github.com/DigiByte-Core/DigiByte.org/pull/111.
